baseurl      = "localhost"
title        = "The Sainpse Institute"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Augmenting Human Intelligence"
  # Home Message
  homeMessage = " We're looking for ways make you smarter, more effective and successful. Join us on a journey through the evolution of augmenting our intuition with machine intelligence. We feel that in order to improve the lives of humans and to accelerate the development of new technologies, AI must intelligently complement human intelligence, not work to replace it."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Sainpse Institute."
    subtitle = "Augmenting Human Intelligence"
    keywords = "AI, Augmented, Intelligence"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "S|A I|NPSE"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "commentary"
    name       = "Commentary"
    url        = "/commentary/"
    weight     = 10

  [[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/Contact/"
    weight     = 20

    